config/routes.rb
Finanzplan::Application.routes.draw do

  resources :contact_messages
  resources :finanzpositions
  

  resources :finanzens

  resources :finanzens
 get "finanzens/index"
  get "finanzens/new"
  get "finanzpositions/index"
  get "impressum/index"	
  get "finanzposition/auswertung"

  get "home/index"

  get "public/index"
  
  root :to => "home#index"
  get "contact_us/view1"
  

  ActiveAdmin.routes(self)

  resources :finanzens
  resources :finanzpositions	
  resources :contact_messages
  devise_for :users

  devise_for :users, :skip => [:registrations]
  
   def after_sign_in_path_for(resource)
        root :to => "home#index"
    end
  
  def after_edit_user_registration_path_for(resource)
        root :to => "home#index"
    end
  def after_create_finanzen(resource) 
	root :to => "finanzposition#index"
end

end

app/models/finanzposition.rb
class Finanzposition < ActiveRecord::Base
  attr_accessible :Art, :Beschreibung, :FinanzenNr, :Wert
  belongs_to :finanzen
  belongs_to :zahlungsart
end

app/controllers/finanzpositions_controller.rb
class FinanzpositionsController < InheritedResources::Base
	 # GET /finanzpositions
  # GET /finanzpositions.json
   #load_and_authorize_resource
def auswertung
   
end
  def index
    #@finanzpositions = Finanzposition.where("FinanzenNr = ?", @finanzens  )
@finanzpositions = Finanzposition.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @finanzpositions }
    end
  end

  # GET /finanzpositions/1
  # GET /finanzpositions/1.json
  def show
    @finanzposition = Finanzposition.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @finanzposition }
    end
  end

  # GET /finanzpositions/new
  # GET /finanzpositions/new.json
  def new
    @finanzposition = Finanzposition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @finanzposition }
    end
  end

  # GET /finanzpositions/1/edit
  def edit
    @finanzposition = Finanzposition.find(params[:id])
  end

  # POST /finanzpositions
  # POST /finanzpositions.json
  def create
    @finanzposition = Finanzposition.new(params[:finanzposition])
    #@finanzposition.users << current_user
    #@finanzposition.FinanzenNr << current_finanzens
    respond_to do |format|
      if @finanzposition.save
        format.html { redirect_to @finanzposition, notice: 'finanzposition was successfully created.' }
        format.json { render json: @finanzposition, status: :created, location: @finanzposition }
      else
        format.html { render action: "new" }
        format.json { render json: @finanzposition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /finanzpositions/1
  # PUT /finanzpositions/1.json
  def update
    @finanzposition = Finanzposition.find(params[:id])

    respond_to do |format|
      if @finanzposition.update_attributes(params[:finanzposition])
        format.html { redirect_to @finanzposition, notice: 'finanzposition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @finanzposition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finanzpositions/1
  # DELETE /finanzpositions/1.json
  def destroy
    @finanzposition = Finanzposition.find(params[:id])
    @finanzposition.destroy

    respond_to do |format|
      format.html { redirect_to finanzpositions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/finanzpositions_helper.rb
module FinanzpositionsHelper
end

app/views/finanzpositions/_form.html.erb
<%= form_for(@finanzposition) do |f| %>
  <% if @finanzposition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finanzposition.errors.count, "error") %> prohibited this finanzposition from being saved:</h2>

      <ul>
      <% @finanzposition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :Art %><br />
<%= f.select :Art, [['Einzahlung','Einzahlung'],['Auszahlung/Ausgabe','Ausgabe']] %>
  </div>
  <div class="field">
    <%= f.label :Position %><br />
    <%= f.text_field :Beschreibung %>
  </div>
  <div class="field">
    <%= f.label :Wert %><br />
    <%= f.text_field :Wert %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finanzpositions/auswertung.html.erb
Auswertung
<h1>Listing finanzpositions</h1>

app/views/finanzpositions/edit.html.erb
<h1>Editing finanzposition</h1>

<%= render 'form' %>

<%= link_to 'Show', @finanzposition %> |
<%= link_to 'Back', finanzpositions_path %>

app/views/finanzpositions/index.html.erb
<h1>Listing finanzpositions</h1>

<table>
  <tr>
    <th>Art</th>
    <th>Beschreibung</th>
    <th>Wert</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @finanzpositions.each do |finanzposition| %>
  <tr>
    
    <td><%= finanzposition.Art %></td>
    <td><%= finanzposition.Beschreibung %></td>
    <td><%= finanzposition.Wert %></td>
    <td><%= link_to 'Show', finanzposition %></td>
    <td><%= link_to 'Edit', edit_finanzposition_path(finanzposition) %></td>
    <td><%= link_to 'Destroy', finanzposition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Finanzposition', new_finanzposition_path %>

app/views/finanzpositions/new.html.erb
<h1>New finanzposition</h1>

<%= render 'form' %>

<%= link_to 'Back', finanzpositions_path %>

app/views/finanzpositions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Finanzennr:</b>
  <%= @finanzposition.FinanzenNr %>
</p>

<p>
  <b>Art:</b>
  <%= @finanzposition.Art %>
</p>

<p>
  <b>Beschreibung:</b>
  <%= @finanzposition.Beschreibung %>
</p>

<p>
  <b>Wert:</b>
  <%= @finanzposition.Wert %>
</p>


<%= link_to 'Edit', edit_finanzposition_path(@finanzposition) %> |
<%= link_to 'Back', finanzpositions_path %>