config/routes.rb
Finanzplan::Application.routes.draw do

  resources :contact_messages
  resources :finanzpositions
  

  resources :finanzens

  resources :finanzens
 get "finanzens/index"
  get "finanzens/new"
  get "finanzpositions/index"
  get "impressum/index"	
  get "finanzposition/auswertung"

  get "home/index"

  get "public/index"
  
  root :to => "home#index"
  get "contact_us/view1"
  

  ActiveAdmin.routes(self)

  resources :finanzens
  resources :finanzpositions	
  resources :contact_messages
  devise_for :users

  devise_for :users, :skip => [:registrations]
  
   def after_sign_in_path_for(resource)
        root :to => "home#index"
    end
  
  def after_edit_user_registration_path_for(resource)
        root :to => "home#index"
    end
  def after_create_finanzen(resource) 
	root :to => "finanzposition#index"
end

end

app/models/contact_message.rb
class ContactMessage < ActiveRecord::Base
  attr_accessible :email, :message, :name
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < InheritedResources::Base

 # GET /contactmessages/1
  # GET /contactmessages/1.json
  def show
    @contact_message = ContactMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact_message }
    end
  end
# GET /contactmessages/new
  # GET /contactmessages/new.json
  def new
    @contact_message = ContactMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_message }
    end
  end

  # POST /contactmessages
  # POST /contactmessages.json
def create
  @contact_message = ContactMessage.new( params[:contact_message])
  if @contact_message.save
      ContactMailer.deliver_confirmation
      flash[:notice] = 'Vielen Dank für Ihre Nachricht.'
      redirect_to(@contact_message)
  else
     render :action => "new"
  end
end
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/views/contact_messages/_form.html.erb
<%= form_for(@contact_message) do |f| %>
  <% if @contact_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_message.errors.count, "error") %> prohibited this contact_message from being saved:</h2>

      <ul>
      <% @contact_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_messages/new.html.erb
<h1>New contact_message</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact_message.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact_message.email %>
</p>

<p>
  <b>Message:</b>
  <%= @contact_message.message %>
</p>


<%= link_to 'Edit', edit_contact_message_path(@contact_message) %> |
<%= link_to 'Back', contact_messages_path %>