config/routes.rb
Finanzplan::Application.routes.draw do

  resources :contact_messages
  resources :finanzpositions
  

  resources :finanzens

  resources :finanzens
 get "finanzens/index"
  get "finanzens/new"
  get "finanzpositions/index"
  get "impressum/index"	
  get "finanzposition/auswertung"

  get "home/index"

  get "public/index"
  
  root :to => "home#index"
  get "contact_us/view1"
  

  ActiveAdmin.routes(self)

  resources :finanzens
  resources :finanzpositions	
  resources :contact_messages
  devise_for :users

  devise_for :users, :skip => [:registrations]
  
   def after_sign_in_path_for(resource)
        root :to => "home#index"
    end
  
  def after_edit_user_registration_path_for(resource)
        root :to => "home#index"
    end
  def after_create_finanzen(resource) 
	root :to => "finanzposition#index"
end

end

app/models/finanzen.rb
class Finanzen < ActiveRecord::Base
  attr_accessible :datum
  has_many :finanzposition
  has_many :user_finanzs 
    has_many :users, through: :user_finanzs
end

app/controllers/finanzens_controller.rb
class FinanzensController < InheritedResources::Base
  # GET /finanzens
  # GET /finanzens.json
   #load_and_authorize_resource

  def index
      @finanzens = Finanzen.all 
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @finanzens }
    end
  end

  # GET /finanzens/1
  # GET /finanzens/1.json
  def show
    @finanzen = Finanzen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @finanzen }
    end
  end

  # GET /finanzens/new
  # GET /finanzens/new.json
  def new
    @finanzen = Finanzen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @finanzen }
    end
  end

  # GET /finanzens/1/edit
  def edit
    #@finanzen = Finanzen.find(params[:id])
  end

  # POST /finanzens
  # POST /finanzens.json
  def create
    @finanzen = Finanzen.new(params[:finanzen])
    #@finanzen.users << current_user

    respond_to do |format|
      if @finanzen.save
        format.html { redirect_to @finanzen, notice: 'finanzen was successfully created.' }
        format.json { render json: @finanzen, status: :created, location: @finanzen }
      else
        format.html { render action: "new" }
        format.json { render json: @finanzen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /finanzens/1
  # PUT /finanzens/1.json
  def update
    @finanzen = Finanzen.find(params[:id])

    respond_to do |format|
      if @finanzen.update_attributes(params[:finanzen])
        format.html { redirect_to @finanzen, notice: 'finanzen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @finanzen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finanzens/1
  # DELETE /finanzens/1.json
  def destroy
    @finanzen = Finanzen.find(params[:id])
    @finanzen.destroy

    respond_to do |format|
      format.html { redirect_to finanzens_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/finanzens_helper.rb
module FinanzensHelper
end

app/views/finanzens/_form.html.erb
<%= form_for(@finanzen) do |f| %>
  <% if @finanzen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finanzen.errors.count, "error") %> prohibited this finanzen from being saved:</h2>

      <ul>
      <% @finanzen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datum %><br />
    <%= f.date_select :datum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finanzens/edit.html.erb
<h1>Editing finanzen</h1>

<%= render 'form' %>

<%= link_to 'Show', @finanzen %> |
<%= link_to 'Back', finanzens_path %>

app/views/finanzens/index.html.erb
<h1>Listing finanzens</h1>

<table>
  <tr>
    <th>Datum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @finanzens.each do |finanzen| %>
  <tr>
    <td><%= finanzen.datum %></td>
    <td><%= link_to 'Anzeigen' %></td>
    <td><%= link_to 'Edit', finanzen%></td>
    <td><%= link_to 'Destroy', finanzen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Finanzen', new_finanzen_path %>

app/views/finanzens/new.html.erb
<h1>New finanzen</h1>

<%= render 'form' %>

app/views/finanzens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Datum:</b>
  <%= @finanzen.datum %>
</p>


<%= link_to 'Weiter', :controller=>"finanzpositions" %> 