config/routes.rb
Finanzplan::Application.routes.draw do

  resources :contact_messages
  resources :finanzpositions
  

  resources :finanzens

  resources :finanzens
 get "finanzens/index"
  get "finanzens/new"
  get "finanzpositions/index"
  get "impressum/index"	
  get "finanzposition/auswertung"

  get "home/index"

  get "public/index"
  
  root :to => "home#index"
  get "contact_us/view1"
  

  ActiveAdmin.routes(self)

  resources :finanzens
  resources :finanzpositions	
  resources :contact_messages
  devise_for :users

  devise_for :users, :skip => [:registrations]
  
   def after_sign_in_path_for(resource)
        root :to => "home#index"
    end
  
  def after_edit_user_registration_path_for(resource)
        root :to => "home#index"
    end
  def after_create_finanzen(resource) 
	root :to => "finanzposition#index"
end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
        if user.has_role?(:admin)
            #Admins
            can :manage, :all
        else
            #Registered users
            can :read, Finanzen do |finanz|
          finanz.users.include? user
      end

            #can :read, Finanzen, :users => user.id

            can :create, Finanzen 
           #can :read, Finanzen, :active => true, :user_id => user.id
            #can :manage, Finanzen, :user => user
            can :manage, Finanzen do |finanz|
          finanzen.users.include? user
      end
        end
    else
        #Guest users
        cannot  :read, :all
    end
end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/asset.rb
class Asset < ActiveRecord::Base
	belongs_to :user
	has_attached_file :asset, :styles => { :large => "640x480", :medium => "300x300", :thumb => "100x100"}
  #attr_accessible :asset_contet_type, :asset_file_name, :asset_file_size, :asset_updated_at, :user_id
end

app/models/contact_mailer.rb
class ContactMailer < ActionMailer::Base

  def confirmation(sent_at = Time.now)
     @subject    = 'Ihre Kontaktnachricht erhalten'
  @body       = {}
  @recipients = 'tanja@test.lu'
  @from       = 'info@railsbuch.de'
  @sent_on    = sent_at
  @headers    = {}

  end

  def message(sent_at = Time.now)
    @subject    = 'ContactMailer#message'
    @body       = {}
    @recipients = ''
    @from       = ''
    @sent_on    = sent_at
    @headers    = {}
  end
end

app/models/contact_message.rb
class ContactMessage < ActiveRecord::Base
  attr_accessible :email, :message, :name
end

app/models/finanzen.rb
class Finanzen < ActiveRecord::Base
  attr_accessible :datum
  has_many :finanzposition
  has_many :user_finanzs 
    has_many :users, through: :user_finanzs
end

app/models/finanzkopf.rb
class Finanzkopf < ActiveRecord::Base
  attr_accessible :datum
  has_many :finanzs
end

app/models/finanzposition.rb
class Finanzposition < ActiveRecord::Base
  attr_accessible :Art, :Beschreibung, :FinanzenNr, :Wert
  belongs_to :finanzen
  belongs_to :zahlungsart
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  belongs_to :user
  has_many :user_finanzs
  has_many :finanzens , through: :user_finanzs
 
  has_many :assets

  attr_accessible :assets_attributes

  accepts_nested_attributes_for :assets, :allow_destroy => true

end

app/models/user_finanz.rb
class UserFinanz < ActiveRecord::Base
  belongs_to :user
  belongs_to :finanzens
  # attr_accessible :title, :body
end

app/models/zahlungsart.rb
class Zahlungsart < ActiveRecord::Base
  attr_accessible :Art
  has_many :finanzposition
end

app/controllers/finanzens_controller.rb
class FinanzensController < InheritedResources::Base
  # GET /finanzens
  # GET /finanzens.json
   #load_and_authorize_resource

  def index
      @finanzens = Finanzen.all 
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @finanzens }
    end
  end

  # GET /finanzens/1
  # GET /finanzens/1.json
  def show
    @finanzen = Finanzen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @finanzen }
    end
  end

  # GET /finanzens/new
  # GET /finanzens/new.json
  def new
    @finanzen = Finanzen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @finanzen }
    end
  end

  # GET /finanzens/1/edit
  def edit
    #@finanzen = Finanzen.find(params[:id])
  end

  # POST /finanzens
  # POST /finanzens.json
  def create
    @finanzen = Finanzen.new(params[:finanzen])
    #@finanzen.users << current_user

    respond_to do |format|
      if @finanzen.save
        format.html { redirect_to @finanzen, notice: 'finanzen was successfully created.' }
        format.json { render json: @finanzen, status: :created, location: @finanzen }
      else
        format.html { render action: "new" }
        format.json { render json: @finanzen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /finanzens/1
  # PUT /finanzens/1.json
  def update
    @finanzen = Finanzen.find(params[:id])

    respond_to do |format|
      if @finanzen.update_attributes(params[:finanzen])
        format.html { redirect_to @finanzen, notice: 'finanzen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @finanzen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finanzens/1
  # DELETE /finanzens/1.json
  def destroy
    @finanzen = Finanzen.find(params[:id])
    @finanzen.destroy

    respond_to do |format|
      format.html { redirect_to finanzens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def impressum
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome Email after save
        UserMailer.welcome_email(@user).deliver
 
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/helpers/finanzens_helper.rb
module FinanzensHelper
end

app/helpers/finanzpositions_helper.rb
module FinanzpositionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/impressum_helper.rb
module ImpressumHelper
end

app/views/contact_us/view1.text.erb
ContactUs#view1

<%= @greeting %>, find me in app/views/app/views/contact_us/view1.text.erb

app/views/contact_us/view2.text.erb
ContactUs#view2

<%= @greeting %>, find me in app/views/app/views/contact_us/view2.text.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finanzplaner</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>


  <div class="container" >
    <div class="row" >

	<div class="span2" style= "padding-top:100px;" >

	<div class="navbar navbar-fixed-left" >
    <div class="navbar-inner" >
      <div class="container" >
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse" >
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <div class="nav-collapse" >
          <ul class="nav" >
            <B><I><ul> Finanzplaner </ul></B></I>
            <BR>
            <BR>
	          <ul><%= link_to "Home" , home_index_path %></ul>
            <BR>
            <ul><%= link_to "Eingabe", new_finanzen_path  %></ul>
            <BR>
            <ul><%= link_to "Berichte/Auswertung","/finanzens" %></ul>
            <BR>
            <ul><%= link_to "Contact Us" %></ul>
            <BR>
            <ul><%= link_to "Impressum", impressum_index_path %></ul>
            <BR>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

      <div class="span8"><%= yield %></div>
      <div class="span2" style= "padding-top:100px;">
        <h2>Login Sachen</h2>
        <% if current_user %>
		<li> Welcome, <%= current_user.email %> ! </li>
    <li> <%= link_to "EDIT Profile", edit_user_registration_path %> </li>
		<B><li> <%= link_to 'Abmelden', destroy_user_session_path, method: :delete %> </li></B>

	<% else %>
		<li> <%= link_to "Anmelden" , new_user_session_path %> </li>
    <li> <%= link_to "Registrieren" , new_user_registration_path %> </li>
	<% end %>
      </div>
    </div>
  </div>
<footer> (c) Fabian Weßling & Jannik van Schaik </footer>
</body>
</html>

app/views/shared/_navigation.html.erb
<html>
<head>
</head>
<body>
	<div class="Contrainer-fluid nav-collapse">
		<ul class="nav">
		 <% if current_user %>
		  <li>Welcome, <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path , :method => :delete %></li>
		  <% else %>
		  <li><%= link_to 'Sign up', new_user_registration_path %>
		  	<%= link_to 'Sign in', new_user_session_path %></li>
		  <% end %>
		</ul>
	</div>
</body>
</html>